multi_imitation_objective:
  _target_: nuplan.planning.training.modeling.objectives.multi_imitation_objective.MultiImitationObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
